name: lint

on:
  push:
    branches: [v1.x]
  pull_request:
    branches: [v1.x]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2.0.1
      - name: Install dependencies
      - run: bun install
      - run: bun run lint
